### ISSUE TITLE
action | dotnet:template:install

### ISSUE THREAD

**Issue by padupe** [alefcarlos/plusultra-dotnet-backstage-plugins#12]
We are getting the following error on our Backstage instance:

```bash
[1] 2023-07-06T14:02:03.940Z Beginning step Install template
[2] 2023-07-06T14:02:03.977Z Error: spawn dotnet ENOENT
[3]     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
[4]     at onErrorNT (node:internal/child_process:476:16)
[5]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Our Template structure:

```yaml
    [...]

    - id: install_template
      name: "Install template"
      action: dotnet:template:install
      input:
        package: ./dotnet-api-example-template
        args:
          - --force

    - id: create_template
      name: "Create template"
      action: dotnet:new
      input:
        template: apiexample
        args:
          - -n
          - ${{ parameters.projectName }}
   
    [...]
```

Follow-up: @jpcarpanezi
