### ISSUE TITLE
action: dotnet:template:install  doesn't support Installation of templates from folder

### ISSUE THREAD

**Issue by tb137** [alefcarlos/plusultra-dotnet-backstage-plugins#9]
Hey,

I have tried to install dotnet template from the folder and it says NO :/

```
- id: donettemplateinstall
      name: Dotnet template install
      action: dotnet:template:install
      input:
        package: ./dotnet/little-template
        args: []
```

Error that I am getting:
```
Command dotnet failed, exit code: 9
12022-10-05T15:38:03.000Z Beginning step Dotnet template install
22022-10-05T15:38:03.000Z The following template packages will be installed:
32022-10-05T15:38:03.000Z ./dotnet/little-template
42022-10-05T15:38:03.000Z ./dotnet/little-template is not supported.
52022-10-05T15:38:03.000Z Error: Command dotnet failed, exit code: 9
6    at ChildProcess.<anonymous> (/home/tms/repos/backstage-app/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:869:11)
7    at ChildProcess.emit (node:events:513:28)
8    at ChildProcess.emit (node:domain:489:12)
9    at maybeClose (node:internal/child_process:1093:16)
10    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

I know for sure that template is valid and working just fine. Also folder "dotnet" exist in the main folder with a list of templates. 

What I would like to have:

1. Ability to install dotnet templates from the folder on the disk (which was fetched from another repo for example)
2. Install multiple templates by pointing to the main folder which contains of several templates.
3. Check if template already exist - otherwise it would fail if you try to add same template...

Thanks ;)
